add modified t-score method
ctlab/ITMO_FS pull request #29
Opened 2020-09-15 15:17 UTC by lindlind

Сделано:

В методе fit реализовал алгоритм из статьи.
Скопировал методы transform и fit_transform из другого метода. Я так понял, это нужно для тестов.
Добавил немного документации по аналогии с другими методами.

Не сделано, появились вопросы:

Не уверен, верную ли папку я выбрал. Соответственно, не изменил файл __init__ в этой папке.

Не разобрался в тестах, совсем не трогал папку test. Куда их добавлять, каким правилам следовать?

Не понял, что конкретно писать в документации в Examples и See also.

2020-09-17 08:00 UTC, LastShekel commented
Первое этот метод явно не unsuprevised он univariate filter. Соответственно ему место в measures в папке Univariate в этом файле лежит все подобные функции которые будет вызвать UnivariateFilter.
для тестирования можешь создать новый файл в папке test или добавить к существующим в univariate_filters_test 
там же найдёшь примеры
в документации example ты пишешь пример применения: код который можно скопировать и он отработает как надо. в see also оставь ссылку на статью.
А так пока хорошо

2020-09-17 18:10 UTC, lindlind commented
С тестами сложно.

Некоторые методы рядом протестированы с помощью соответствующего метода в библиотеке sklearn. "gini_index" плохо протестирован, там стоят только ассерты на проверку, что ответ входит в адекватный диапазон. "su_measure", вообще не протестирован.

Мой алгоритм в sklearn не реализован. Я вообще не нашел его реализации на питоне. Я тоже проверил, что значения лежат в адекватном диапазоне, чтобы хоть что-то проверить. Как протестировать лучше?

2020-09-22 09:34 UTC, LastShekel requested changes

2020-09-22 09:34 UTC, LastShekel commented on ITMO_FS/filters/univariate/measures.py
> +import pandas as pd
мы не можем использовать pandas здесь
он только в тесте может быть

2020-09-22 09:34 UTC, LastShekel commented on ITMO_FS/filters/univariate/measures.py
> +    corr_with_others = abs(pd.DataFrame(X).corr()).fillna(0).to_numpy()
мы не можем использовать pandas здесь
можешь посмотреть на другие корреляции которые есть в этом же файле

2020-09-22 11:20 UTC, lindlind commented on ITMO_FS/filters/univariate/measures.py
> +import pandas as pd
fixed

2020-09-22 11:21 UTC, lindlind commented on ITMO_FS/filters/univariate/measures.py
> +    corr_with_others = abs(pd.DataFrame(X).corr()).fillna(0).to_numpy()
fixed

2020-09-22 18:50 UTC, LastShekel commented
Хорошо, добавь тот же тест но чтобы использовалось твоя функция в составе univariate filter, и ещё тест с UnivariateFilter но входные данные будут pandas data frame

2020-09-24 18:01 UTC, merged